set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CLANG_TRIPLE x86_64-linux-gnu)

find_program(CLANG_PATH NAMES clang)
if(${CLANG_PATH} STREQUAL "CLANG_PATH-NOTFOUND")
  message(SEND_ERROR "Unable to find clang")
endif()

find_program(CLANGXX_PATH NAMES clang++)
if(${CLANG_PATH} STREQUAL "CLANGXX_PATH-NOTFOUND")
  message(SEND_ERROR "Unable to find clang++")
endif()

set(CMAKE_C_COMPILER "${CLANG_PATH}" CACHE FILEPATH "")
set(CMAKE_C_COMPILER_TARGET "${CLANG_TRIPLE}")

set(CMAKE_CXX_COMPILER "${CLANGXX_PATH}" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_TARGET "${CLANG_TRIPLE}")

if(NOT $ENV{VCPKG_TOOLCHAIN} STREQUAL "")
  message(STATUS "Included VCPKG: $ENV{VCPKG_TOOLCHAIN}")
  include($ENV{VCPKG_TOOLCHAIN})
endif()
